services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-container
    hostname: nginx-oauth
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_SECRET}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_SERVE_CONFIG=/config/stirling.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/config:/config
      - tailscale-volume:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx-container
    network_mode: service:tailscale
    depends_on:
      - tailscale

volumes:
  tailscale-volume:
    driver: local
