services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: nginx-basic
    environment:
      - TS_AUTHKEY=tskey-auth-kiTJhVJRMB21CNTRL-rHSB6vKHsLTb5g1W1cKkRTTSh7pfGfkk
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-volume:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx-basic:
    image: nginx
    network_mode: service:tailscale
volumes:
  tailscale-volume:
    driver: local
