services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-container
    hostname: mealie
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_SECRET}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_SERVE_CONFIG=/config/mealie.json.hardcoded
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/config:/config
      - tailscale-volume:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0
    container_name: mealie-container
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - mealie-data:/app/data
    environment:
      - ALLOW_SIGNUP=true
    restart: unless-stopped

volumes:
  tailscale-volume:
    driver: local
  mealie-data:
    driver: local
